import { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
} from "react-native";
import { router } from "expo-router";
import api from "../../services/api";

export default function WarningReportScreen() {
  const [students, setStudents] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAtRiskStudents();
  }, []);

  const fetchAtRiskStudents = async () => {
    try {
      const response = await api.get("/admin/students/");
      // Filter only at risk and non compliant students
      const atRisk = response.data.students.filter(
        (s) => s.status === "at_risk" || s.status === "non_compliant",
      );
      setStudents(atRisk);
    } catch (error) {
      Alert.alert("Error", "Failed to load warning report");
    } finally {
      setLoading(false);
    }
  };

  const getStatusColour = (status) => {
    if (status === "at_risk") return "#FF9800";
    return "#F44336";
  };

  const getStatusLabel = (status) => {
    if (status === "at_risk") return "At Risk";
    return "Non Compliant";
  };

  const getWarningMessage = (student) => {
    const remaining = Math.max(0, 20 - student.total_hours).toFixed(1);
    if (student.status === "at_risk") {
      return `Needs ${remaining} more hours to meet weekly requirement.`;
    }
    return `Significantly below required hours. Needs ${remaining} more hours immediately.`;
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#FF9800" />
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Text style={styles.backButton}> Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Warning Report</Text>
        <View style={{ width: 60 }} />
      </View>

      {/* Institution Header */}
      <View style={styles.institutionHeader}>
        <Text style={styles.institutionName}>Tertiary College</Text>
        <Text style={styles.institutionSubtitle}>Auckland, New Zealand</Text>
        <Text style={styles.reportTitle}>At-Risk Student Warning Report</Text>
        <Text style={styles.reportDate}>
          Generated: {new Date().toLocaleDateString("en-NZ")}
        </Text>
      </View>

      {/* Summary */}
      <View style={styles.summaryCard}>
        <Text style={styles.summaryText}>
          Total students requiring attention: {students.length}
        </Text>
      </View>

      {/* Student Cards */}
      <View style={styles.card}>
        {students.length === 0 ? (
          <Text style={styles.noData}>
            No at-risk students this week. All students are compliant.
          </Text>
        ) : (
          students.map((student, index) => (
            <View key={index} style={styles.studentCard}>
              <View style={styles.studentHeader}>
                <View>
                  <Text style={styles.studentName}>{student.student_name}</Text>
                  <Text style={styles.studentId}>ID: {student.student_id}</Text>
                </View>
                <View
                  style={[
                    styles.statusBadge,
                    { backgroundColor: getStatusColour(student.status) },
                  ]}
                >
                  <Text style={styles.statusText}>
                    {getStatusLabel(student.status)}
                  </Text>
                </View>
              </View>
              <View style={styles.hoursRow}>
                <Text style={styles.hoursLabel}>Hours completed</Text>
                <Text style={styles.hoursValue}>
                  {student.total_hours}/20 hrs
                </Text>
              </View>
              <Text style={styles.warningMessage}>
                {getWarningMessage(student)}
              </Text>
              <TouchableOpacity
                style={styles.letterButton}
                onPress={() =>
                  router.push({
                    pathname: "/(admin)/warning-letter",
                    params: {
                      studentName: student.student_name,
                      studentId: student.student_id,
                      totalHours: student.total_hours,
                      status: student.status,
                    },
                  })
                }
              >
                <Text style={styles.letterButtonText}>Generate Letter</Text>
              </TouchableOpacity>
            </View>
          ))
        )}
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Generated by TrackX Attendance System
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A1A2E",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1A1A2E",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    paddingTop: 50,
    backgroundColor: "#16213E",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  backButton: {
    color: "#4CAF50",
    fontSize: 16,
  },
  institutionHeader: {
    backgroundColor: "#16213E",
    padding: 20,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#FF9800",
    marginBottom: 15,
  },
  institutionName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
  },
  institutionSubtitle: {
    fontSize: 14,
    color: "#999",
    marginTop: 4,
  },
  reportTitle: {
    fontSize: 16,
    color: "#FF9800",
    marginTop: 10,
    fontWeight: "600",
  },
  reportDate: {
    fontSize: 12,
    color: "#999",
    marginTop: 6,
  },
  summaryCard: {
    backgroundColor: "#2A1A0A",
    margin: 15,
    marginBottom: 0,
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: "#FF9800",
  },
  summaryText: {
    color: "#FF9800",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  card: {
    margin: 15,
  },
  studentCard: {
    backgroundColor: "#16213E",
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#FF9800",
  },
  studentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  studentName: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "bold",
  },
  studentId: {
    color: "#999",
    fontSize: 12,
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  statusText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
  },
  hoursRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  hoursLabel: {
    color: "#999",
    fontSize: 13,
  },
  hoursValue: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "500",
  },
  warningMessage: {
    color: "#FF9800",
    fontSize: 12,
    marginTop: 4,
  },
  noData: {
    color: "#4CAF50",
    fontSize: 14,
    textAlign: "center",
    padding: 20,
  },
  footer: {
    padding: 20,
    alignItems: "center",
  },
  footerText: {
    color: "#999",
    fontSize: 12,
  },
  letterButton: {
    backgroundColor: '#F44336',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    marginTop: 10,
},
letterButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
},
});
