# Generated by Django 6.0.7 on 2026-08-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='checkins/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
