# Generated by Django 6.0.7 on 2026-09-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0004_user_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField()),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('teams_students_found', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lecturer')),
            ],
            options={
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamsImportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('discrepancy_campus_only', 'Discrepancy - Campus Only'), ('discrepancy_teams_only', 'Discrepancy - Teams Only'), ('absent', 'Absent')], max_length=30)),
                ('action', models.TextField()),
                ('on_campus', models.BooleanField(default=False)),
                ('in_teams', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='attendance.teamsimportsession')),
            ],
            options={
                'ordering': ['student__full_name'],
            },
        ),
    ]
